[package]
name = "deepmesa-collections"
version = "0.12.0"
authors = ["Rahul Singh <rsingh@arrsingh.com>"]
edition = "2018"
categories = [
	"data-structures",
]
description = "A collection of data structures and algorithms designed for performance"
readme = "README.md"
license = "MIT OR Apache-2.0"
documentation = "https://docs.rs/deepmesa-collections"
homepage = "https://www.arrsingh.com/deepmesa-collections"
repository = "https://github.com/deepmesa/collections-rs"


[lib]
doc = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dev-dependencies]
rand = "0.8.3"
