[package]
name = "deepmesa-lists"
version = "0.1.0"
authors = ["arrsingh"]
edition = "2018"

[lib]
doc = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dev-dependencies]
deepmesa = {path = "../"}